In [66]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

# Your code for Task 1 here:
arr1_1=np.arange(0,100,1)
arr1_2=np.vstack(([1,1,1],[1,1,1],[1,1,1]))
arr1_3=np.vstack(([7,7,7,7],[7,7,7,7]))
arr1_4=np.random.randint(10,50,size=(4,4))
print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])



# Your code for Task 2 here:
 #2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
val2_1=data[2,3]
print("the element at row 2, column 3 (0-indexed).",val2_1)
# 2.2 Extract the first row. Store it in 'row2_2'.
row2_2=data[0,:]
print("the first row.",row2_2)
print("the last column")
# 2.3 Extract the last column. Store it in 'col2_3'.
for i in range(0,4):
  col2_3=data[i,3]
  print(col2_3)
# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
a=data[1,:]
b=data[2,:]
for i in range(0,4):
  c=data[i,0]
for i in range(0,4):
  d=data[i,1]
sub_arr2_4=[(a,b),(c,d)]
print(sub_arr2_4)
# Task 2.5: Indexing and Slicing with Arrays
import numpy as np
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
filtered_element2_5=data>100
print("filtered_element2_5:",data[filtered_element2_5])


# Task 3: Conditional Operations
import numpy as np
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.
print(arr3_1,end=" ")
for i in range(4):
  for j in range(5):
     if arr3_1[i][j]<10:
       arr3_1[i][j]=0
     else:
       arr3_1[i]=arr3_1[i]
print(arr3_1,end=" ")


# 3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.
import numpy as np
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))
print(arr3_1,end=" ")
print("3.2 task")
count=0
for i in range(4):
  for j in range(5):
    if arr3_1[i][j]%2==0:
      count=count+1
even_count3_3=[]
even_count3_3.append(count)
print(even_count3_3)
# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

print("# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.")
sum4_1=[]
sum4_1=np.sum(arr4_1)
print("sum:",sum4_1)
print("# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.")
mean_cols4_2=[]
mean_cols4_2=[(np.mean(arr4_1[:,0])),
(np.mean(arr4_1[:,1])),
(np.mean(arr4_1[:,2]))]
print(mean_cols4_2)
print("# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.")
max_rows4_3=[]
max_rows4_3=[(np.max(arr4_1[0,:])),
             (np.max(arr1_4[:,1])),
             (np.max(arr4_1[:,2]))]
print(max_rows4_3)
print("# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'")
std4_4=np.std(arr4_1)
print(std4_4)
# Your code for Task 4 here:
# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
reshaped_arr5_2=[]
reshaped_arr5_2=np.arange(24).reshape(4,6)
print(reshaped_arr5_2)
# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
reshaped_arr5_3=[]
reshaped_arr5_3=np.arange(24).reshape(2,3,4)
print(reshaped_arr5_3)
# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
flattened_arr5=[]
flattened_arr5=reshaped_arr5_2.flatten()
print(flattened_arr5)
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).
flattened_arr5=reshaped_arr5_2.ravel()
print(flattened_arr5)
# Your code for Task 5 here:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
result6_1=[]
result6_1=arr6_1+scalar
print(result6_1,end="\n")
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_2=[]
result6_2=arr6_1+vector
print(result6_2)
# Your code for Task 6 here:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])
print(original_arr7)
# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
#     Modify the first element of 'view_arr7' to 99.
#     Observe how 'original_arr7' changes.
view_arr7=original_arr7[:]
view_arr7[0]=99
print(view_arr7)
# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
#     Modify the last element of 'copy_arr7' to 0.
#     Observe how 'original_arr7' remains unchanged.
copy_arr7=[]
copy_arr7=original_arr7.copy()
copy_arr7[-1]=0
print(copy_arr7)
# Your code for Task 7 here:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
arr1=np.vstack(arr8_a)
arr2=np.vstack(arr8_b)
vstack_arr8_1=[arr1,
               arr2]
print(vstack_arr8_1,end="\n")
# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
hstack_arr8_2=[]
hstack_arr8_2=[()]
# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.

# Your code for Task 8 here:



# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.

# Your code for Task 9 here:






--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[38 15 33 42]
 [39 15 38 45]]

--- Task 2: Indexing and Slicing with Arrays ---
the element at row 2, column 3 (0-indexed). 120
the first row. [10 20 30 40]
the last column
40
80
120
160
[(array([50, 60, 70, 80]), array([ 90, 100, 110, 120])), (np.int64(130), np.int64(140))]

--- Task 2: Indexing and Slicing with Arrays ---
filtered_element2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
[[20 11  4 15  2]
 [ 8  4 19 14 13]
 [ 3 19 13 14  1]
 [13 17 15  7 12]] [[20 11  0 15  0]
 [ 0  0 19 14 13]
 [ 0 19 13 14  0]
 [13 17 15  0 12]] 
--- Task 3: Conditional Operations ---
[[ 9  2  7 13  5]
 [17 17 10 20 11]
 [16 20  7  5 12]
 [16  6  7  1 18]] 3.2 task
[9]



In [81]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).

# Your code for Task 1 here:
arr1_1=np.arange(0,100,1)
arr1_2=np.vstack(([1,1,1],[1,1,1],[1,1,1]))
arr1_3=np.vstack(([7,7,7,7],[7,7,7,7]))
arr1_4=np.random.randint(10,50,size=(4,4))
print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])



# Your code for Task 2 here:
 #2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
val2_1=data[2,3]
print("the element at row 2, column 3 (0-indexed).",val2_1)
# 2.2 Extract the first row. Store it in 'row2_2'.
row2_2=data[0,:]
print("the first row.",row2_2)
print("the last column")
# 2.3 Extract the last column. Store it in 'col2_3'.
for i in range(0,4):
  col2_3=data[i,3]
  print(col2_3)
# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
a=data[1,:]
b=data[2,:]
for i in range(0,4):
  c=data[i,0]
for i in range(0,4):
  d=data[i,1]
sub_arr2_4=[(a,b),(c,d)]
print(sub_arr2_4)
# Task 2.5: Indexing and Slicing with Arrays
import numpy as np
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
filtered_element2_5=data>100
print("filtered_element2_5:",data[filtered_element2_5])


# Task 3: Conditional Operations
import numpy as np
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.
print(arr3_1,end=" ")
for i in range(4):
  for j in range(5):
     if arr3_1[i][j]<10:
       arr3_1[i][j]=0
     else:
       arr3_1[i]=arr3_1[i]
print(arr3_1,end=" ")


# 3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.
import numpy as np
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))
print(arr3_1,end=" ")
print("3.2 task")
count=0
for i in range(4):
  for j in range(5):
    if arr3_1[i][j]%2==0:
      count=count+1
even_count3_3=[]
even_count3_3.append(count)
print(even_count3_3)
# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

print("# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.")
sum4_1=[]
sum4_1=np.sum(arr4_1)
print("sum:",sum4_1)
print("# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.")
mean_cols4_2=[]
mean_cols4_2=[(np.mean(arr4_1[:,0])),
(np.mean(arr4_1[:,1])),
(np.mean(arr4_1[:,2]))]
print(mean_cols4_2)
print("# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.")
max_rows4_3=[]
max_rows4_3=[(np.max(arr4_1[0,:])),
             (np.max(arr1_4[:,1])),
             (np.max(arr4_1[:,2]))]
print(max_rows4_3)
print("# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'")
std4_4=np.std(arr4_1)
print(std4_4)
# Your code for Task 4 here:
# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
reshaped_arr5_2=[]
reshaped_arr5_2=np.arange(24).reshape(4,6)
print(reshaped_arr5_2)
# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
reshaped_arr5_3=[]
reshaped_arr5_3=np.arange(24).reshape(2,3,4)
print(reshaped_arr5_3)
# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
flattened_arr5=[]
flattened_arr5=reshaped_arr5_2.flatten()
print(flattened_arr5)
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).
flattened_arr5=reshaped_arr5_2.ravel()
print(flattened_arr5)
# Your code for Task 5 here:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
result6_1=[]
result6_1=arr6_1+scalar
print(result6_1,end="\n")
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_2=[]
result6_2=arr6_1+vector
print(result6_2)
# Your code for Task 6 here:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])
print(original_arr7)
# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
#     Modify the first element of 'view_arr7' to 99.
#     Observe how 'original_arr7' changes.
view_arr7=original_arr7[:]
view_arr7[0]=99
print(view_arr7)
# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
#     Modify the last element of 'copy_arr7' to 0.
#     Observe how 'original_arr7' remains unchanged.
copy_arr7=[]
copy_arr7=original_arr7.copy()
copy_arr7[-1]=0
print(copy_arr7)
# Your code for Task 7 here:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
arr1=np.vstack(arr8_a)
arr2=np.vstack(arr8_b)
vstack_arr8_1=[arr1,
               arr2]
print(vstack_arr8_1,end="\n")
# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
hstack_arr8_2=[]
hstack_arr8_2=[(np.hstack(arr8_a)),(np.hstack(arr8_b))]
print(hstack_arr8_2)
# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
combined_arr8_3 = np.concatenate((arr8_a, arr8_b, arr8_c), axis=0)
print(combined_arr8_3)
# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.
print(np.array_split(combined_arr8_3,3))
# Your code for Task 8 here:



# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
stored_arr9_1=[]
stored_arr9_1=np.sort(arr9_1)
print(stored_arr9_1)
# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
sorted_cols9_2=[]
sorted_cols9_2=[(np.sort(arr9_2d[:,0])),np.sort(arr9_2d[:,1]),(np.sort(arr9_2d[:,2]))]
print(sorted_cols9_2)
# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
idx9_3=np.argwhere(arr9_1==9)
print(idx9_3)
# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.
max_idx9_4=np.argwhere(arr9_1==np.max(arr9_1))
print(max_idx9_4)
# Your code for Task 9 here:






--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[26 21 28 20]
 [11 33 30 31]]

--- Task 2: Indexing and Slicing with Arrays ---
the element at row 2, column 3 (0-indexed). 120
the first row. [10 20 30 40]
the last column
40
80
120
160
[(array([50, 60, 70, 80]), array([ 90, 100, 110, 120])), (np.int64(130), np.int64(140))]

--- Task 2: Indexing and Slicing with Arrays ---
filtered_element2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
[[20 10  2 11 10]
 [14 11 15 11 13]
 [ 7 13  5 17  4]
 [ 4  5 10  8  3]] [[20 10  0 11 10]
 [14 11 15 11 13]
 [ 0 13  0 17  0]
 [ 0  0 10  0  0]] 
--- Task 3: Conditional Operations ---
[[ 2 12  1 18 15]
 [ 8  8 15 14  1]
 [ 4 17 11 16  4]
 [ 7  4 11 19  8]] 3.2 task
[11]
